### ISSUE TITLE
Some protocol example?

### ISSUE THREAD

**Issue by GGRei** [r-efi/r-efi#30]
Firstly, thank for your job. My skill with rust language is low level, can you give a good practise example with **r_efi crate** to locate the gop protocol ( with boot_services ) and use the query_mode method of GOP?

It will be really appreciated.

**Comment by dvdhrm** [comment]
Generally, I recommend reading the C examples from EDK2 TianoCore. They should be easy to transpose into Rust, as `r-efi` just follows whatever the standard provides.

Anyway, I will see whether I can write a short example to use the GOP protocol.

**Comment by dvdhrm** [comment]
You can find the example here:

https://github.com/r-efi/r-efi/blob/main/examples/gop-query.rs

Please note that this just highlights that you really ought to create helpers that make UEFI programming in Rust a lot easier. The r-efi crate just provides you all the spec details, but is quite cumbersome to use directly.

**Comment by GGRei** [comment]
Well, I try this after reading some example ( like https://wiki.osdev.org/GOP ) this program compile but return an error at execution :

```
#![no_main]
#![no_std]

extern crate r_efi;

use r_efi::efi;
use core::ptr;
use core::mem::MaybeUninit;

static mut SYSTEM_TABLE: MaybeUninit<efi::SystemTable> = MaybeUninit::uninit();

pub fn system_table() -> &'static efi::SystemTable {

  unsafe { &*SYSTEM_TABLE.as_ptr() }

}

pub fn boot_services() -> &'static efi::BootServices {

  unsafe { &*system_table().boot_services }

}

pub fn con_out() -> &'static efi::protocols::simple_text_output::Protocol {

  unsafe { &*system_table().con_out }
}


#[export_name = "efi_main"]
pub extern fn main(_h: efi::Handle, st: *mut efi::SystemTable) -> efi::Status {

    unsafe { SYSTEM_TABLE = MaybeUninit::new(st.read()) }

    let detecting = [
        0x0047u16, 0x004Fu16, 0x0050u16, // GOP
        0x0020u16, // " "
        0x0049u16, 0x004Eu16, 0x0049u16, 0x0054u16, 0x0049u16, 0x0045u16, 0x0044u16, // INITIED
        0x000au16, // "\n"
        0x0000u16, // NUL
    ];

    let mut gop_guid = efi::protocols::graphics_output::PROTOCOL_GUID;
    let null_ptr: *mut core::ffi::c_void = ptr::null_mut();
    let gop: *mut efi::protocols::graphics_output::Protocol = ptr::null_mut();
    
    let stats = (boot_services().locate_protocol)(
        &mut gop_guid,
        null_ptr,
        gop as *mut _ as *mut *mut core::ffi::c_void,
    );

    if stats.is_error(){
        
        return stats;

    }else{

        (con_out().output_string)(
            unsafe { (*st).con_out },
            detecting.as_ptr() as *mut efi::Char16,   
        );

    }

    unsafe {
        let mut x: usize = 0;
        ((*(*st).boot_services).wait_for_event)(1, &mut (*(*st).con_in).wait_for_key, &mut x)
    };
    
    efi::Status::SUCCESS

}

#[panic_handler]
fn rust_panic_handler(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}
```

But this example doesn't work. I have an error and the :

```
 if stats.is_error(){
        
        return stats;

    }
```

Return nothing on my UEFI console. ( Maybe need to use the output_string protocol to display on the screen the status? )

I have understand how use UEFI with OSDev documentation or EDK2 documentation but Im pettry sure its my rust skill the problem.

**Comment by GGRei** [comment]
Oh you having posted an example! 

Sorry and thank for your help, I going study your example.

**Comment by GGRei** [comment]
It's really helpful. I understand better now.

Thanks for the example!

**Comment by dvdhrm** [comment]
> It's really helpful. I understand better now.
> 
> Thanks for the example!

Sure! Let me know if anything else is unclear!

**Comment by GGRei** [comment]
Yes please, why use : 

`.locate_handle_buffer`

instead of simple :

`.locate_protocol`

?

**Comment by dvdhrm** [comment]
> Yes please, in your example, why use :
> 
> `.locate_handle_buffer and .handle_protocol`
> 
> instead of simple :
> 
> `.locate_protocol`
> 
> ?

Mostly to show how to use the lowlevel functions. In this example, the `LocateProtocol` helper would suffice, you are right.

**Comment by GGRei** [comment]
Thanks for your help, its ok for me and the gop protocol now.
However, I have a other question if you accepted? 

I try to load an .elf file with my bootloader and in my code below, how can obtain the buffer size :

`let mut file_info_size: usize = 0;`

The buffer must be aligned before? if yes, how?

```
 let mut file_info_size: usize = 0;
        let mut file_info: *mut boot_infos::FileInformations = ptr::null_mut();
        let mut guid_file_info: efi::Guid = efi::protocols::file::INFO_ID;

        s = unsafe { ((*loaded_file).get_info)(
            loaded_file,
            &mut guid_file_info as *mut _,
            &mut file_info_size,
            ptr::null_mut(),
 )};
```

Here the entiere code to understand my work. If you have some advice. Do not hesitate! Thank again for your help!


```
/*
| Handling loaded image UEFI protocol
*/

    let mut loaded_image: *mut efi::protocols::loaded_image::Protocol = ptr::null_mut();
    let mut guid_loaded_image: efi::Guid = efi::protocols::loaded_image::PROTOCOL_GUID;

    let mut s = (boot_services().handle_protocol)(
        h,
        &mut guid_loaded_image as *mut _,
        &mut loaded_image as *mut _ as *mut *mut core::ffi::c_void,
    );

    match s {

        efi::Status::SUCCESS => { "..." },
        _ => panic!(),

    }

/*
| Handling simple file system UEFI protocol
*/

    let mut file_system: *mut efi::protocols::simple_file_system::Protocol = ptr::null_mut();
    let mut guid_file_system: efi::Guid = efi::protocols::simple_file_system::PROTOCOL_GUID;

    s = (boot_services().handle_protocol)(
        unsafe { (*loaded_image).device_handle },
        &mut guid_file_system as *mut _,
        &mut file_system as *mut _ as *mut *mut core::ffi::c_void,
    );

    match s {

        efi::Status::SUCCESS => { "..." },
        _ => panic!(),

    }

/*
| Try to open and read kernel file
*/

    let mut directory: *mut efi::protocols::file::Protocol = ptr::null_mut();
    let mut loaded_file: *mut efi::protocols::file::Protocol = ptr::null_mut();

    unsafe { ((*file_system).open_volume)(
        file_system,
        &mut directory,
    ) };

    s = unsafe { ((*directory).open)(
        directory,
        &mut loaded_file,
        kernel_name_file.as_ptr() as *mut efi::Char16,
        efi::protocols::file::MODE_READ,
        efi::protocols::file::READ_ONLY,
    )};

    if s.is_error(){

      "..."

    }else{

        let mut file_info_size: usize = 0;
        let mut file_info: *mut boot_infos::FileInformations = ptr::null_mut();
        let mut guid_file_info: efi::Guid = efi::protocols::file::INFO_ID;

        s = unsafe { ((*loaded_file).get_info)(
            loaded_file,
            &mut guid_file_info as *mut _,
            &mut file_info_size,
            ptr::null_mut(),
        )};

        if s.is_error(){

             "..."

        }else{

        s = (boot_services().allocate_pool)(
                efi::MemoryType::LoaderData,
                file_info_size,
                &mut file_info as *mut _ as *mut *mut core::ffi::c_void,
            );
        }

        if s.is_error(){

           "..."

        }else{

        s = unsafe { ((*loaded_file).get_info)(
                loaded_file,
                &mut guid_file_info as *mut _,
                &mut file_info_size,
                &mut file_info as *mut _ as *mut core::ffi::c_void,
            )};
   }       
}
```

**Comment by dvdhrm** [comment]
> I try to load an .elf file with my bootloader and in my code below, how can obtain the buffer size to return at "**efi::protocol::file::protocol::get_info()**" :
> 
> `let mut file_info_size: usize = 0;` // <- its wrong, need to return the buffer_size but how?
> 
> The buffer must be aligned before? if yes, how?

I am not entirely sure I understand your problem. The `GetInfo()` function should set `file_info_size` to the required size when returning `EFI_BUFFER_TOO_SMALL`. Does it not do that for you?

An alternative approach is to set the buffer size to some initial value like 128-bytes, and then duplicate it for as long as it returns `EFI_BUFFER_TOO_SMALL`.

Lastly, where did you get the requirement that the buffer must be aligned? Only if you access it as a particular struct the buffer needs to be aligned. Regardless, if you use `AllocatePool()` (or other allocators), you _always_ get suitably aligned buffers. So in those cases you do not need to care about alignment problems.

**Comment by GGRei** [comment]
> I am not entirely sure I understand your problem. The GetInfo() function should set file_info_size to the required size when returning EFI_BUFFER_TOO_SMALL. Does it not do that for you?

Yep, i thinked too the **GetInfo() function** return the size of buffer like the **query_mode() function** with the GOP protocol, but apparently no. The **efi::Status** value of the **GetInfo() function** return `EFI_BUFFER_TOO_SMALL` error.

> An alternative approach is to set the buffer size to some initial value like 128-bytes, and then duplicate it for as long as it returns EFI_BUFFER_TOO_SMALL.

Hmm duplicate it? You mean increase the value size?

> Lastly, where did you get the requirement that the buffer must be aligned? Only if you access it as a particular struct the buffer needs to be aligned. Regardless, if you use AllocatePool() (or other allocators), you always get suitably aligned buffers. So in those cases you do not need to care about alignment problems.

Thx for this infos ! and for your help!

**Comment by dvdhrm** [comment]
> > I am not entirely sure I understand your problem. The GetInfo() function should set file_info_size to the required size when returning EFI_BUFFER_TOO_SMALL. Does it not do that for you?
> 
> Yep, when the EFI_BUFFER_TOO_SMALL` value status is returned by the GetInfo() function, the function don't acquired the size of the buffer and I don't know why.

Can you elaborate? What does `don't acquired the size of the buffer` mean? Does it return 0?

> > An alternative approach is to set the buffer size to some initial value like 128-bytes, and then duplicate it for as long as it returns EFI_BUFFER_TOO_SMALL.
> 
> Hmm duplicate it? You mean increase the value size? Can you explain?

You allocate a buffer of size 128 and pass it to the function. If it returns `TOO_SMALL`, you duplicate the buffer size to 256 and try again. You do this until it works out.

> > Lastly, where did you get the requirement that the buffer must be aligned? Only if you access it as a particular struct the buffer needs to be aligned. Regardless, if you use AllocatePool() (or other allocators), you always get suitably aligned buffers. So in those cases you do not need to care about alignment problems.
> 
> Thx for this infos ! and for your help!

Sure! Note that there are lots of buggy UEFI implementations out there, so often it is more about testing what works, than actually doing what the spec says ;)

**Comment by GGRei** [comment]
> > > I am not entirely sure I understand your problem. The GetInfo() function should set file_info_size to the required size when returning EFI_BUFFER_TOO_SMALL. Does it not do that for you?
> > 
> > 
> > Yep, when the EFI_BUFFER_TOO_SMALL` value status is returned by the GetInfo() function, the function don't acquired the size of the buffer and I don't know why.
> 
> Can you elaborate? What does `don't acquired the size of the buffer` mean? Does it return 0?
> 
.


The buffersize return 94 for me but If I initalize it and allocate 128 manually, like as you advised me, its ok now. thanks ^^

.

> > > An alternative approach is to set the buffer size to some initial value like 128-bytes, and then duplicate it for as long as it returns EFI_BUFFER_TOO_SMALL.
> > 
> > 
> > Hmm duplicate it? You mean increase the value size? Can you explain?
> 
> You allocate a buffer of size 128 and pass it to the function. If it returns `TOO_SMALL`, you duplicate the buffer size to 256 and try again. You do this until it works out.
> 
> > > Lastly, where did you get the requirement that the buffer must be aligned? Only if you access it as a particular struct the buffer needs to be aligned. Regardless, if you use AllocatePool() (or other allocators), you always get suitably aligned buffers. So in those cases you do not need to care about alignment problems.
> > 
> > 
> > Thx for this infos ! and for your help!
> 
> Sure! Note that there are lots of buggy UEFI implementations out there, so often it is more about testing what works, than actually doing what the spec says ;)

Yeah I see that. :) Thanks again for your help!

**Comment by GGRei** [comment]
Maybe it may require an upgrade of the r_efi extension but for example, when you use the `efi::protocols::file::Info`

In the Struct :
```
pub struct Info {
    pub size: u64,
    pub file_size: u64,
    pub physical_size: u64,
    pub create_time: crate::system::Time,
    pub last_access_time: crate::system::Time,
    pub modification_time: crate::system::Time,
    pub attribute: u64,
    pub file_name: [crate::base::Char16],
}
```
`pub file_name` ( and potentially all [Char16] array ) can be problematic during compilation :

`let mut file_info: *mut efi::protocols::file::Info = ptr::null_mut();`

_the size for values of type `[u16]` cannot be known at compilation time
within `r_efi::protocols::file::Info`, the trait `Sized` is not implemented for `[u16]`_

A solution can be to fixe the array size in the structure like :
`pub file_name: [crate::base::Char16; n]` but it isn't a lasting solution for a crate. You can duplicate the info structure and fixe the array size but not really efficient either. 

Maybe an implementation of struct with `core::trait::Sized` would be appropriate?

**Comment by dvdhrm** [comment]
Right, raw pointers to unsized types are still fat-pointers in rust. This is quite unfortunate. I looked for recommendations on how to _easily_ handle those uncomplete types in rust FFI, but there seems to be no consensus. Things like `rust-bindgen` generate `IncompleteArrayType` types which provide required accessors.

What we currently have will definitely not work out, since we will be unable to represent pointers to those types.

We already skip the trailing field in some structures, to make them easily embeddable. The spec is quite inconsistent in that regard as well. I am tempted to just apply this everywhere. We can then always readd them in the future, if we figured out a way to represent them.

What do you think?

**Comment by GGRei** [comment]
I must admit that I am not well competent on the subject. But maybe try what you suggest and apply everywhere? 
Can you give an example of the solution you are proposing? Would help me better understand the thing.

**Comment by dvdhrm** [comment]
> I must admit that I am not well competent on the subject. But maybe try what you suggest and apply everywhere?
> Can you give an example of the solution you are proposing? Would help me better understand the thing.

I now pushed the change. I decided to just use empty arrays. You need unsafe code to access those, anyway, so an empty array looked like the best option:

c80b51a596f0ef83f222dc753603e86f6a8016a2

Also, feel free to open new issues if you encounter other problems! This makes it easier to track and work with.

Thanks again for the report! I totally missed that those types don't work on the ABI.

**Comment by GGRei** [comment]
Well, thanks at you for your support! Really appreciated. :)

**Comment by GGRei** [comment]
Hello dvdhrm :)

Im sorry to disturb you again, but I need a lastime your help if you accepted. Well, Im always blocked to load my executable file with EFI. 

Firstly, I have absolutely no error or warning during all execution of my work.

To explain the situation this is how I proceed ( I have intentionally removed the status results conditions for a most clear code ): 

```
/*
| Handling loaded image UEFI protocol
*/

    let mut loaded_image: *mut efi::protocols::loaded_image::Protocol = ptr::null_mut();
    let mut guid_loaded_image: efi::Guid = efi::protocols::loaded_image::PROTOCOL_GUID;

    let mut s = (boot_services().handle_protocol)(
        h,
        &mut guid_loaded_image as *mut _,
        &mut loaded_image as *mut _ as *mut *mut core::ffi::c_void,
    );



/*
| Handling simple file system UEFI protocol
*/

    let mut file_system: *mut efi::protocols::simple_file_system::Protocol = ptr::null_mut();
    let mut guid_file_system: efi::Guid = efi::protocols::simple_file_system::PROTOCOL_GUID;

    s = (boot_services().handle_protocol)(
        unsafe { (*loaded_image).device_handle },
        &mut guid_file_system as *mut _,
        &mut file_system as *mut _ as *mut *mut core::ffi::c_void,
    );



/*
| Try to open and read data
*/

    let mut directory: *mut efi::protocols::file::Protocol = ptr::null_mut();
    let mut loaded_file: *mut efi::protocols::file::Protocol = ptr::null_mut();

    s = unsafe { ((*file_system).open_volume)(
        file_system,
        &mut directory,
    ) };

s = unsafe { ((*directory).open)(
        directory,
        &mut loaded_file,
        kernel_name_file.as_ptr() as *mut efi::Char16,
        efi::protocols::file::MODE_READ,
        efi::protocols::file::READ_ONLY,



/*
| Check the Elf64 header file
*/
        let mut file_info_size: usize = 128;
        let mut file_info: *mut efi::protocols::file::Info = ptr::null_mut();
        let mut guid_file_info: efi::Guid = efi::protocols::file::INFO_ID;

        s = unsafe { ((*loaded_file).get_info)(
            loaded_file,
            &mut guid_file_info as *mut _,
            &mut file_info_size,
            ptr::null_mut(),
        )};


// Allocate memory pool for data

s = (boot_services().allocate_pool)(
                efi::LOADER_DATA,
                file_info_size,
                &mut file_info as *mut _ as *mut *mut core::ffi::c_void,
            );


// PROBLEM START HERE withe the buffer itself ( file_info )
 s = unsafe { ((*loaded_file).get_info)(
                loaded_file,
                &mut guid_file_info as *mut _,
                &mut file_info_size,
                &mut file_info as *mut _ as *mut core::ffi::c_void,
            )};
```

the **get_info** function return a success status, the buffersize ( **file_info_size** ) return some info like 102 ( depend the size of the executable name example for **kernel.elf**, the buffersize return 102. If I test with the name : **main.elf**, buffersize return 98 ).

But if I wanna use the buffer himself ( **file_info** ), all is empty.

```
(*file_info).file_size : return 0.
(*file_info).file_name : return nothing
(*file_info).create_time : return 0

let create_time_info: &efi::Time = unsafe { &(*file_info).create_time };
(*create_time_info).year : return 0
```
I have absolutely no idea what is the problem. In the past, all your advice have resolved my problems. If you have time to help me one more time?

Thanks!

**Comment by dvdhrm** [comment]
@GGRei I am on parental leave until 2022. I suggest opening a separate github-issue, maybe other people can chime in.

**Comment by GGRei** [comment]
Ok, :) All my best wishes for you and for your family. :)
