### ISSUE TITLE
Proposal for providing MIT as optional License

### ISSUE THREAD

**Issue by Ayush1325** [r-efi/r-efi#32]
Hello everyone, I am currently working on point Rust std to UEFI. 

As such, I would like to use this crate and [r-efi-alloc](https://github.com/r-efi/r-efi-alloc) in the Rust std. The current licensing of this project, however, is not completely compatible with the Rust std licensing. From what I understand, it is mostly due to the fact that the base Apache-2.0 license is incompatible with GPLv2. (https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/3)

So I would like to propose adding MIT as an optional license. Alternatively, it might be fine if it was under Apache-2.0 with the LLVM exception as well, although I am not completely sure about that.

**Comment by dvdhrm** [comment]
I added this now. Given that r-efi is just a transpose of the spec, I think there is little reason not to do this.

Thanks for looking into porting the rust compiler! If there is anything we can do to help, let us know!

**Comment by dvdhrm** [comment]
(I have not pushed a release, yet. If you need one, I can do that. Otherwise, I just defer this a bit in case we get some more changes.)

**Comment by Ayush1325** [comment]
@dvdhrm Thanks for the change.

Pushing a new release is not needed yet. I will be making a few PRs before it is ready for use with std.
