### ISSUE TITLE
Publish a new release of r-efi

### ISSUE THREAD

**Issue by Ayush1325** [r-efi/r-efi#47]
Hi @dvdhrm. It would be great if you could publish a new release of `r-efi`. Also, the PR for Rust std for UEFI has been opened [here](https://github.com/rust-lang/rust/pull/100316).

**Comment by dvdhrm** [comment]
(I am traveling for at least 6 more days, I will publish a release afterwards)

**Comment by Ayush1325** [comment]
Hi @dvdhrm, any ETA on when you will be able to push a new release?

**Comment by dvdhrm** [comment]
I just pushed out v4.1.0 to crates.io!
