### ISSUE TITLE
Should PI Protocols be added to this crate

### ISSUE THREAD

**Issue by Ayush1325** [r-efi/r-efi#56]
Currently, only the Protocols present in UEFI spec seem to be defined in this crate. However, there are some valuable protocols like `EFI_MP_SERVICE_PROTOCOL` that are present in PI spec and, as far as I know, are available in the Dxe phase as well. So is it acceptable to add those to this crate, or should there be a separate crate for PI spec stuff?

There is also the UEFI shell spec which also contains protocols that can be pretty useful when writing shell applications, so I was wondering where they should go as well?

**Comment by dvdhrm** [comment]
I think all of the UEFI specs are fine to be integrated into `r-efi`. There are some uefi-forum specs like ACPI which probably should go into a separate module, as they are useful outside of UEFI environments. But other than that, I am fine incorporating this into `r-efi`.
