### ISSUE TITLE
Include GUID definitions for the ACPI RSDP structure

### ISSUE THREAD

**Issue by GRMorgan** [r-efi/r-efi#63]
Hi,

Looking through the current code base I cannot see anywhere that defines the ACPI RSDP GUIDs for use in looking up the ACPI table index in the configuration_table. These are defined in the ACPI spec v6.5 (linked below) on page 98 in section **5.2.5.2 -  Finding the RSDP on UEFI Enabled Systems**. These values are:

- ACPI 1.0: eb9d2d30-2d88-11d3-9a16-0090273fc14d
- ACPI 2.0: 8868e871-e4f1-11d3-bc22-0080c73c8881

These should probably be added to make looking through these tables less error prone.

https://uefi.org/sites/default/files/resources/ACPI_Spec_6_5_Aug29.pdf

Thanks,
Gareth

**Comment by GRMorgan** [comment]
Apologies that isn't the latest spec. It is on page 98, section 4.6.1.1 of the latest one

https://uefi.org/sites/default/files/resources/UEFI_Spec_2_10_Aug29.pdf

**Comment by dvdhrm** [comment]
Right, I remember reading this section and deciding not to transpose it, given that it is explicitly marked as non-exhaustive in the spec with no intention for completeness. It is a list of relevant external specifications known at the time of spec-release, but the definitions are not really part of the UEFI spec but it merely refers to the definitions in the respective external specifications.

Note that `r-efi` is a quite mechanical crate that merely transposes the EFI namespace from the spec to rust. We try to avoid any human input, hence I am very unsure whether to include these definitions. Additionally, some of the entries don't even use the `EFI_*` namespace.

Can you elaborate what you would use these definitions for? In particular, if you interact with ACPI, you very likely already have a crate / module with definitions from the ACPI specifications, which then would be the better place to include those GUIDs, wouldn't it?

**Comment by GRMorgan** [comment]
I've currently written my own code for handling both the GUIDs and the ACPI tables. The GUID only exists for comparison to the vendor_guid field in ConfigurationTable. When the GUID matches the one you are looking for you can retrieve vendor_table as the physical address of the ACPI RSDP. It plays no part in ACPI itself, only in the look up in the UEFI ConfigurationTable.

https://docs.rs/r-efi/latest/r_efi/system/struct.ConfigurationTable.html

I had to work out how the GUIDs map onto the values I was seeing in the docs by reading how r-efi itself uses them. From a design perspective I dislike putting the GUID in ACPI because:
1. ACPI has no concept of these GUIDs itself. So you end up needing to pull in part of UEFI into an ACPI crate. Effectively making r-efi a dependency of r-acpi
2. ACPI doesn't use these values at all in non-EFI scenarios. They are purely for identifying the type of table within the UEFI configuration table context. In BIOS mode for instance you search specific memory ranges for a certain 16 byte aligned 8-byte long string value

So my view is if these don't belong in r-efi then you would need some kind of r-efi-acpi (or maybe r-efi-extras) that just contains these two GUIDs and includes r-efi, though not necessarily r-acpi, as a dependency. Or the user would have to figure out how to write the GUID themselves.

**Comment by dvdhrm** [comment]
Uff, forgot about this, thanks for the patience. So I did 2 things:

 - `Guid::from_bytes()` now allows creating `Guid` types from the byte representation. External tools can thus define Guids according to the UUID spec. If they have an `as_bytes()` function, or allow transmute, then you can now easily use them from `r-efi` based modules, without requiring code dependencies either way. Note that the `r-efi` types have a guaranteed memory layout according to the UEFI spec, so it is always safe to transmute **to** them, as long as your source has any such guarantees. A simple `u128` definitions is thus sufficient to transmute to `efi::Guid`.
 - I imported all the missing EFI configuration tables, which are included in recent spec releases. Not sure why I missed them initially.
 - I added a separate section with all the Guids from external industry standards, as listed in the specification. This is now limited to anything listed in the spec, as this seems reasonable to include (as you explained above).

Let me know if you have any comments! I will close this as completed, but if anything is missing, I can reopen it!
