### ISSUE TITLE
Use GitHub repo releases to track releases

### ISSUE THREAD

**Issue by makubacki** [r-efi/r-efi#69]
It would be convenient to have the release to crates.io correspond to a repo version with release notes showing the changes that went into the release. We could also use GitHub APIs to parse the information for a given release.

I see a release GitHub workflow was added recently. Do you think this is something that could happen as part of the release process?

**Comment by dvdhrm** [comment]
The `publish.yml` workflow now uses `gh release create [...]` to publish releases to GitHub. It will extract the release-notes from NEWS.md.
